version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./imc:/var/www/html/wp-content/themes/imc

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
